### PR TITLE
List supported methods in same groups and order as webmozart/assert does

### PR DESCRIPTION
**Pull request by herndlm**
just an idea to ease comparison with https://github.com/webmozarts/assert to figure out which methods are still missing

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
What about removing this list altogether? It's just hard to maintain. Some assertions are already supported out of the box thanks to assert PHPDoc tags.

**Comment by herndlm** [comment]
yeah, fine with me, I only wanted to use it as an example to show what is still missing so that one of the other open issues can be closed. I'll just modify this PR then to remove it and post in that issue directly :)

**Comment by herndlm** [comment]
adapted

**Comment by ondrejmirtes** [comment]
Thank you. We could do the same thing in https://github.com/phpstan/phpstan-beberlei-assert

**Pull request merged**
