### PR TITLE
Support list type

### PR DESCRIPTION
**Pull request by herndlm**
This is for after PHPStan 1.9.0 was released :)

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Nice! Thank you :)

**Comment by ondrejmirtes** [comment]
On the other hand, this will stop make it work without bleedingEdge? We should test both...

**Comment by herndlm** [comment]
I can split bleedingEdge tests into a dedicated test class if you prefer that

**Comment by ondrejmirtes** [comment]
Yes, please do :)

**Comment by herndlm** [comment]
Second thought was doing it in the same test class but a dedicated bleedingEdge type file. I'll see what works best

**Comment by ondrejmirtes** [comment]
Needs to be a separate file akin to `tests/Type/WebMozartAssert/AssertTypeSpecifyingExtensionTest.php`. Because you need to return different getAdditionalConfigFiles.

**Pull request merged**
