### PR TITLE
Add allKeyExists tests

### LINKED ISSUE #46: Internal type conversion from array to iterable.
After updating my dependencies I'm experiencing problems with analysis. Array types seem to be converted internally to iterable types when calling webmozart/assert methods. I've added screenshots and my system information. Hopefully this helps, if you need more information, ping me :-)

```
class Logic
{
    /**
     * @param array<int, array<string, mixed>> $items
     */
    public function execute(array $items): void
    {
        \Webmozart\Assert\Assert::allKeyExists($items, 'id');

        // ...

        $this->executeSomethingElse($items); // ERROR: Now phpstan says that $items has become an iterable.
    }

    /**
     * @param array<int, array<string, mixed>> $items
     */
    public function executeSomethingElse(array $items): void
    {
    }
}
```

image

System information:

```
bash-5.1$ php -v
PHP 7.4.16 (cli) (built: Mar 25 2021 23:24:45) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies
    with Xdebug v3.0.3, Copyright (c) 2002-2021, by Derick Rethans
```

image

### PR DESCRIPTION
**Pull request by herndlm**
Closes #46 by showing that this has been fixed already. I think. If wrong - maybe somebody can point me in the direction to reproduce it to create  a failing test?

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Can you bisect when this was fixed and why it didn't work on April 23rd? (The date on the original issue.) Basically I want you to find the commit where the test still fails, thanks.

**Comment by herndlm** [comment]
Strange, same result on all 0.12.8 (Dec 20), 0.12.9, 0.12.10, 0.12.11, 0.12.12 (Jan), 0.12.13, 0.12.14, 0.12.15 (July), 0.12.16 (Aug). I get
```
 ------ --------------------------------------------------------------- 
  Line   foo.php                                                        
 ------ --------------------------------------------------------------- 
  13     Dumped type: array<array('id' => int)>                         
  17     Dumped type: array<int, array<string, mixed>&hasOffset('id')>  
  21     Dumped type: array<array&hasOffset('id')>                      
 ------ --------------------------------------------------------------- 
```
Same thing by requiring the same version of phpstan that was reported (0.12.84)

Can this be something else? Not sure what else could be checked if I can't even find the "bad" state basically to do a real bisect 🤔

**Comment by ondrejmirtes** [comment]
No idea, but issue needs to be reproduced before we can consider it fixed.

**Comment by herndlm** [comment]
@waltertamboer it's been a while since you opened the issue, but do you maybe still know more about it?

**Comment by ondrejmirtes** [comment]
There's now a conflict in this PR, please rebase, thanks.

**Comment by ondrejmirtes** [comment]
Thank you.

**Comment by waltertamboer** [comment]
Sorry @herndlm - Missed the notifications, good job :+1:

**Comment by herndlm** [comment]
@waltertamboer no worries, I did not fix anything here though. I just added tests that show that it is working fine right now. And I was not able to find out why or when it was broken.
Please let us know if the original issue is still relevant!

**Pull request merged**
