### PR TITLE
Update slevomat/coding-standard to ^8.0

### PR DESCRIPTION
**Pull request by herndlm**
looks like you're other repos might be in need of this too. Let me know if you want more PRs. Sometimes these simple, repetitive tasks in between are like meditation anyways.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Not sure why Renovate doesn't pick this up :)

**Comment by ondrejmirtes** [comment]
Oh it did :D https://github.com/phpstan/phpstan-webmozart-assert/pull/141

**Comment by ondrejmirtes** [comment]
Thank you.

**Comment by herndlm** [comment]
yeah, renovate couldn't handle that both packages need to be changed at the same time :)

**Pull request merged**
