### PR TITLE
Extract remaining tests

### PR DESCRIPTION
**Pull request by herndlm**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Conflicts here. Feel free to do a single PR with all these changes so that there are no more conflicts.

**Comment by herndlm** [comment]
Rebased this PR, cherry-picking the other stuff in and squashing it into a single commit.
This removes the data.php file completely.

I'm just not a 100% happy with the inconsistency of the collection and nullable assertion tests. all assertions can be used with collections and nullables (as in `all*` and `nullOr*`) and we have a few tested in collections.php while the even fewer nullable assertions are just next to their "normal" tests. I was thinking of moving collection assertions next do their normal asserts too. Or the other way around (creating a nullable.php). A few of those tests, as we have them right now, should be fine I guess, as they all work the same way. But maybe I'm overthinking the cleanup now :)

**Comment by herndlm** [comment]
sorry for my impatience, can we merge this? :) I'd love to get the remaining 2 count assertions in afterwards

**Comment by ondrejmirtes** [comment]
Thank you :)

**Pull request merged**
