### PR TITLE
check integerish values

### PR DESCRIPTION
**Pull request by mavimo**

### CODE REVIEW

**Comment by mavimo** [comment]
This may need rebase once #2 is merged

The failure is fixed in #4

**Comment by ondrejmirtes** [comment]
This is weird - the result should lead to `int|string`. Can you rebase and investigate why it isn't the case? Thanks.

**Comment by mavimo** [comment]
@ondrejmirtes I'll check ASAP, thx for feedback

**Comment by mavimo** [comment]
@ondrejmirtes was a typo, `integrish` instead of `integerish` (missing E after G)
~~Also added an extra fix since CI is broken~~

**Comment by ondrejmirtes** [comment]
Thanks!

**Pull request merged**
