### PR TITLE
add support for inArray and oneOf

### PR DESCRIPTION
**Pull request by ntzm**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
It should work, see: https://phpstan.org/r/79660277-e10e-4a44-9b8b-ed1f709a7622

You have a typo in the test (`$al` vs. `$am`):

```php
		Assert::nullOrInArray($al, ['foo', 'bar']);
		$am;
```

**Comment by ntzm** [comment]
Wow... I spent 30 mins looking at it and didn't notice the typo. Thanks!

**Comment by ondrejmirtes** [comment]
Thank you!

**Comment by ondrejmirtes** [comment]
You can also look at other low-hanging fruit :) https://github.com/phpstan/phpstan-webmozart-assert/issues/39 + https://github.com/phpstan/phpstan-webmozart-assert/issues/45

**Pull request merged**
